# Generated by Django 2.2.5 on 2019-09-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.SmallIntegerField(max_length=5)),
                ('Weakness', models.SmallIntegerField(max_length=5)),
                ('Confidence', models.SmallIntegerField(max_length=5)),
                ('Interest', models.SmallIntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('dashboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='negotiation.DashBoard')),
            ],
            bases=('negotiation.dashboard',),
        ),
    ]
