# Generated by Django 2.2.5 on 2019-09-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonfactor',
            name='Confidence',
        ),
        migrations.RemoveField(
            model_name='commonfactor',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='commonfactor',
            name='Strength',
        ),
        migrations.RemoveField(
            model_name='commonfactor',
            name='Weakness',
        ),
    ]
